version: "3.8"
services:
  api:
    container_name: api
#    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_PORT=5000
      - MONGO_HOSTNAME=mongodb
      - JWT_SECRET=kdojfiwouewfkjop
      - JWT_LIFETIME=60000
      - MONGO_PORT=27017
      - MONGO_USERNAME=rootuser
      - MONGO_PASSWORD=rootpass
      - MONGO_DB=mydb
      - MONGODB_URI=mongodb://mongodb/mydb
    ports:
      - 5000:8080
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - /Users/Sayner/github_repos/spring-mongodb-rest-api/api/data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  data: {}
networks:
  default:
    name: mongodb_network